lib/concentrate/encoder/trip_updates_enhanced.ex
lib/concentrate/parser/gtfs_realtime_enhanced.ex
lib/concentrate/stop_time_update.ex
test/concentrate/parser/gtfs_realtime_enhanced_test.exs
test/concentrate/stop_time_update_test.exs

Why:
* To include platform_id in output.
* Asana link: https://app.asana.com/0/516686971504018/518860404232401
This change addresses the need by:
* Editing `Concentrate.Parser.GTFSRealtimeEnhanced` to
support stop_time_update's `platform_id`.
* Editing `Concentrate.StopTimeUpdate` to include `platform_id` in the
output of `merge/2`.
* Editing `Concentrate.Encoder.TripUpdatesEnhanced` to include
`platform_id` in output.

Parse platform_id from TripUpdates_enhance.json

---

config/config.exs
lib/concentrate/encoder/trip_updates/json.ex
test/concentrate/encoder/trip_updates/json_test.exs

Why:
* For trip updates to also be available in JSON.
* Asana link: https://app.asana.com/0/505721188639414/523237115785966
This change addresses the need by:
* Editing config to include a new encoder/file for generating
TripUpdates.json files.
* Adding `Concentrate.Encoder.TripUpdates.JSON` which leverages
`Concentrate.Encoder.TripUpdates` for the actual work. Only difference
between `TripUpdates` and `TripUpdates.JSON` is that the latter
returns JSON.

Adds TripUpdates.json encoder

---

config/config.exs
lib/concentrate/encoder/vehicle_positions/json.ex
test/concentrate/encoder/vehicle_positions/json_test.exs

Why:
* For vehicle positions to also be available in JSON.
* Asana link: https://app.asana.com/0/505721188639414/523237115785967
This change addresses the need by:
* Editing config to include a new encoder/file for generating
VehiclePositions.json files.
* Adding `Concentrate.Encoder.VehiclePositions.JSON` which leverages
`Concentrate.Encoder.VehiclePositions` for the actual work. Only difference
between `VehiclePositions` and `VehiclePositions.JSON` is that the latter
returns JSON.

Adds VehiclePositions.json encoder

---

lib/concentrate.ex
lib/concentrate/producer/http.ex
lib/concentrate/producer/http/state_machine.ex
lib/concentrate/supervisor/pipeline.ex
test/concentrate/producer/http/state_machine_test.exs
test/concentrate/supervisor/pipeline_test.exs
test/concentrate_test.exs

For some URLs, there's a fallback URL we can use if the parent URL stops
updating. We implement this by having a child StateMachine that we can pass
messages to when we're in fallback mode.

fallback URLs for the StateMachine

---

lib/concentrate.ex
lib/concentrate/parser/gtfs_realtime.ex
lib/concentrate/supervisor/pipeline.ex
test/concentrate/parser/gtfs_realtime_test.exs
test/concentrate_test.exs

Some feeds make predictions well into the future, and we don't care about those predictions. This allows us to configure that time on a per-feed basis.

allow filtering a feed to a maximum future time

---

semaphore/deploy.sh

If we stop the old service, we'll stop producing new files. Instead, we spin
up the new instance and wait for it to take over from the previous service.

update deploy script to not stop the old service

---

lib/concentrate/encoder/gtfs_realtime_helpers.ex
lib/concentrate/encoder/trip_updates.ex
lib/concentrate/encoder/trip_updates_enhanced.ex
test/concentrate/encoder/trip_updates/json_test.exs
test/concentrate/encoder/trip_updates_enhanced_test.exs

Most are scheduled, so we don't need to include the extra data.

don't render SCHEDULED schedule_relationships

---

lib/concentrate/producer/http/state_machine.ex
lib/concentrate/sink/s3.ex
test/concentrate/producer/http/state_machine_test.exs
test/concentrate/sink/s3_test.exs

We get these occasionally (see https://github.com/benoitc/hackney/issues/464). In the meantime, we can treat them as other kinds of `closed` errors.
* `HTTP.StateMachine`: retry the fetch
* `Sink.S3` log a warning, but don't retry
asana: https://app.asana.com/0/116562505129567/471912272390965

better handling for `{:ssl_closed, _}` errors

---

lib/concentrate/filter.ex
lib/concentrate/filter/closed_stop.ex
lib/concentrate/filter/include_route_direction.ex
lib/concentrate/filter/round_speed_to_integer.ex
lib/concentrate/filter/vehicle_with_no_trip.ex
test/concentrate/filter/closed_stop_test.exs
test/concentrate/filter/include_route_direction_test.exs
test/concentrate/filter/round_speed_to_integer_test.exs
test/concentrate/filter/vehicle_with_no_trip_test.exs
test/concentrate/filter_test.exs

Now that the filters which need state are `GroupFilter`s, we can simplify the
implementation of `Filter` to not require additional state.

remove `init/0` callback from Filter

---

lib/concentrate/reporter.ex
lib/concentrate/reporter/latency.ex
lib/concentrate/reporter/stop_time_update_latency.ex
lib/concentrate/reporter/vehicle_latency.ex
lib/concentrate/supervisor/pipeline.ex
test/concentrate/reporter/latency_test.exs
test/concentrate/reporter/stop_time_update_latency_test.exs
test/concentrate/reporter/vehicle_latency_test.exs

Since there's additional filtering happening after the grouping, the
reporters weren't aware of it. By having the reporters work on grouped data,
they receive it only after all the filtering happens.

`Reporter`: work with trip groups instead of a list of parsed items

---

lib/concentrate/encoder/gtfs_realtime_helpers.ex
lib/concentrate/parser/gtfs_realtime.ex
test/concentrate/encoder/gtfs_realtime_helpers_test.exs
test/concentrate/encoder/trip_updates_enhanced_test.exs
test/concentrate/parser/gtfs_realtime_test.exs

Instead of ignoring them, we'll keep them but only if their status isn't
`SCHEDULED`.

fix for TripUpdate w/o StopTimeUpdates

---

lib/concentrate/merge_filter.ex
test/concentrate/merge_filter_test.exs

This gives the sources some time to load their first set of data.
@cwh711 this was your idea (and a good one!) so you get to do the review :)

MergeFilter: delay initial timeout

---

lib/concentrate/supervisor/pipeline.ex
test/concentrate/supervisor/pipeline_test.exs

Previously, we were filtering it out before it was passed to the parser.

pass `excluded_routes` param to the parser

---

lib/concentrate/group_filter/remove_unneeded_times.ex
test/concentrate/group_filter/remove_unneeded_times_test.exs

In some cases, the MBTA extends a train past where the schedule says the
train should go. In that case, we get additional StopTimeUpdates past the
original last stop. Previously, the RemoveUnneededTimes filter would remove
the departure time from the scheduled last stop, even though it's not
actually the last stop. 
This updates the filter to only remove the departure
time if the stop is also the last in the group.

don't remove the departure time except from the last stop

---

lib/concentrate/alert/informed_entity.ex
lib/concentrate/filter/alert/cancelled_trips.ex
lib/concentrate/filter/alert/shuttles.ex
lib/concentrate/filter/alert/time_table.ex
lib/concentrate/group_filter/shuttle.ex
test/concentrate/filter/alert/cancelled_trips_test.exs
test/concentrate/filter/alert/shuttles_test.exs
test/concentrate/group_filter/shuttle_test.exs
test/concentrate/parser/gtfs_realtime_enhanced_test.exs
test/support/filter/fakes.ex

In the Enhanced JSON feed, alert InformedEntities have a list of activities the entity is related to. For shuttles, we can use this keep the last arrival for a train to the stop which is being shuttled.
- InformedEntities with activities BOARD and EXIT: skip the stop since riders can neither board or exit at that stop
- BOARD but not EXIT - only affects boarding, so remove the departure time
- EXIT but not BOARD - prevents passengers from being on the train before this stop, so remove the arrival time

better support for shuttles (via activities)

---

lib/concentrate/parser/gtfs_realtime_enhanced.ex

Because Access has to do a runtime lookup of the module to use, it's more
efficient to use `Map.get` directly (if slightly more verbose).
```elixir
iex> a = %{a: 1}
iex> :timer.tc fn -> Enum.each(0..1000000, fn _ -> Map.get(a, :a) end) end
{814540, :ok}
iex> :timer.tc fn -> Enum.each(0..1000000, fn _ -> a[:a] end) end
{1115298, :ok}

use Map instead of Access to work with maps

---

lib/concentrate/filter/gtfs/stops.ex
lib/concentrate/filter/gtfs/supervisor.ex
lib/concentrate/filter/gtfs/unzip.ex
lib/concentrate/stop_time_update.ex
test/concentrate/filter/gtfs/stops_test.exs
test/concentrate/stop_time_update_test.exs

In the future, we'll be uising different stop IDs for each track/platform:
they'll share a parent station ID. This updates the merging algorithm for
`StopTimeUpdate` to combine them, based on the parent station ID.

support merging different stop IDs

---

config/config.exs
lib/concentrate/group_filter/vehicle_stop_match.ex
test/concentrate/group_filter/vehicle_stop_match_test.exs

When we assign the trip to a track, we want the vehicle to also use that stop ID.
Follow-on work to #53.

filter to match VehiclePosition stop_id to StopTimeUpdate

---

lib/concentrate/group_filter/shuttle.ex
test/concentrate/group_filter/shuttle_test.exs

Previously, the behavior for shuttles at the start of trips was to cancel the
entire trip. However, this isn't the desired behavior: trips skipped at the
beginning are generally running the second part of the trip.
The new behavior is to only skip the stop times at the beginning. If boarding
is available at the last stop in the shuttle, then that stop will not be
skipped but instead only lose its `arrival_time`.

better handling of shuttles at the start of trips

---

Dockerfile

Erlang 21 has an issue with `ehmon`, a library we use for logging system information. By going back to Elixir 1.6.5 and Erlang 20, we avoid the issue for now.
I deployed this to dev, and you can see the start of the errors when `master` was deployed, followed by the end of the errors when this branch is deployed, [here](https://mbta.splunkcloud.com/en-US/app/search/search?earliest=1530528022&latest=1530535222&q=search%20index%3Dconcentrate-dev%20(%22%5Berror%5D%22%20OR%20%22%5Bwarn%5D%22)%20%7C%20eval%20error%3Dif(like(_raw%2C%20%22%25%20%5Berror%5D%20%25%22)%2C%201%2C%200)%20%7C%20timechart%20sum(error)%20as%20errors&display.page.search.mode=fast&dispatch.sample_ratio=1&display.general.type=visualizations&display.page.search.tab=visualizations&display.visualizations.charting.chart=column& …

pin build to Elixir 1.6.5/Erlang 20

---

lib/concentrate/parser/gtfs_realtime_enhanced.ex
test/concentrate/parser/gtfs_realtime_enhanced_test.exs

Previously we left it as a binary, which then failed to encode as a PB file later.
Changes are mostly to add better testing for decoding a JSON VehiclePositions file into our internal structures.

convert binary vehicle status to an atom

---

lib/concentrate/encoder/gtfs_realtime_helpers.ex
lib/concentrate/encoder/trip_updates.ex
lib/concentrate/encoder/trip_updates_enhanced.ex
lib/concentrate/parser/gtfs_realtime.ex
lib/concentrate/parser/gtfs_realtime_enhanced.ex
lib/concentrate/stop_time_update.ex
semaphore/deploy.sh
test/concentrate/parser/gtfs_realtime_test.exs
test/concentrate/stop_time_update_test.exs

It turns out that Swiftly uses an `uncertainty` value of 300 for predictions which are based on the schedule, and Transit also knows how to handle that value.

pass uncertainty values through the pipeline

---

.tool-versions
Dockerfile
lib/concentrate.ex
lib/concentrate/parser/gtfs_realtime.ex
lib/concentrate/producer/http/state_machine.ex
lib/concentrate/supervisor/pipeline.ex
test/concentrate/parser/gtfs_realtime_test.exs
test/concentrate_test.exs

Some upstream sources require passing headers for authentication. These changes allow us to configure those headers and pass them through to the upstream server.

allow configuring headers for sources

---

lib/concentrate/group_filter/vehicle_stop_match.ex
test/concentrate/group_filter/vehicle_stop_match_test.exs

Haven't been able to find the root cause of the crash from over the weekend, but this should prevent it from happening again.

don't crash if the VP or STU don't have a stop_id

---

lib/concentrate/filter/gtfs/unzip.ex
test/concentrate/filter/gtfs/unzip_test.exs

Handle GTFS files which start with the UTF-8 Byte Order Mark.
References #74

strip a BOM from the GTFS data

---

lib/concentrate/filter/gtfs/pickup_drop_off.ex
lib/concentrate/group_filter/remove_unneeded_times.ex
test/concentrate/filter/gtfs/pickup_drop_off_test.exs
test/concentrate/group_filter/remove_unneeded_times_test.exs

Previously, we'd treat extra stop IDs as being able to both pickup and drop
off riders. However, that's not always true: if we're running the vehicle
further, it may have extra stops beyond the sequence specified in GTFS. In
that case, we don't want to make any changes.

don't treat added stops as always having pickup and drop off

---

.tool-versions
Dockerfile

Seeing if going back to 21.1 avoids the SSL errors we've been seeing.

revert to Erlang 21.1

---

lib/concentrate/encoder/gtfs_realtime_helpers.ex
lib/concentrate/parser/gtfs_realtime.ex
lib/concentrate/trip_update.ex
test/concentrate/parser/gtfs_realtime_test.exs

The vehicle itself is only on a single trip at a time, but a TripUpdate can
predict that a vehicle will be running that trip in the future. Previously,
we'd throw that information away, relying on the information from the
VehiclePosition to hold the trip information. Now, we also keep track of
the vehicle's ID on the TripUpdate, and use that if there isn't a
VehiclePosition with that trip ID.

feat: track the same vehicle for multiple TripUpdates

---

lib/concentrate/stop_time_update.ex
test/concentrate/stop_time_update_test.exs

Otherwise, we end up in the situation where we've removed the times and set
the `schedule_relationship` to `SKIPPED`, but the `status` still says that
the vehicle is "On time".

fix: strip `status` from skipped StopTimeUpdates

---

Dockerfile

Per
https://engineeringblog.yelp.com/2016/01/dumb-init-an-init-for-docker.html,
running the Erlang VM as PID 1 may have some issues with reaping child
processes. `dumb-init` replaces PID 1 and runs our VM as another PID.

feat: use dumb-init to run the main process

---

lib/concentrate/merge_filter.ex
test/concentrate/merge_filter_test.exs

According to the [GTFS-RT spec](https://gtfs.org/reference/realtime/v2/#message-tripupdate):
> At least one stop_time_update must be provided for the trip unless the
trip.schedule_relationship is CANCELED - if the trip is canceled, no
stop_time_updates need to be provided.
We allowing this when we grouped the TripUpdates, but not when filtering.

fix: don't strip empty CANCELED TripUpdates when merging

---

lib/concentrate/filter/round_speed_and_bearing.ex
test/concentrate/filter/round_speed_and_bearing_test.exs
test/concentrate/parser/helpers_test.exs

This changes the VehiclePosition filter from truncating to rounding to one decimal place. 
It does change the value from an int to a float, so it _could_ be a breaking change, though the test suite passed and I didn't see any immediate way it would cause issues in the API.
Since the module was named `RoundSpeedToInteger`, I had to rename it (and then rename the file as well). I thought of just `RoundSpeed` at first, but the module also rounds the bearing, so I figured I could add that to the name, too. (Or tease it out into a separate `RoundBearing` filter, but since they were already together I figured I should just leave it that way.)

feat: round vehicle speeds to one decimal place, don't truncate them

---

lib/concentrate/encoder/gtfs_realtime_helpers.ex
lib/concentrate/encoder/trip_updates_enhanced.ex
lib/concentrate/parser/gtfs_realtime.ex
lib/concentrate/parser/gtfs_realtime_enhanced.ex
lib/concentrate/trip_update.ex
test/concentrate/encoder/trip_updates_enhanced_test.exs
test/concentrate/encoder/trip_updates_test.exs
test/concentrate/parser/gtfs_realtime_enhanced_test.exs
test/concentrate/trip_update_test.exs

If `route_pattern_id` are present in `TripUpdate`, parse them and include them in enhanced output.

Include route_pattern_id in TripUpdate

---

lib/concentrate/encoder/gtfs_realtime_helpers.ex
lib/concentrate/encoder/trip_updates.ex
test/concentrate/encoder/trip_updates/json_test.exs
test/concentrate/encoder/trip_updates_test.exs

For StopTimeUpdate records in the Protobuf export, we don't include the
`status` field. This can result in records like this:
```
entity {
id: "CR-Weekday-Fall-19-616"
trip_update {
trip {
trip_id: "CR-Weekday-Fall-19-616"
start_date: "20191210"
route_id: "CR-Needham"
direction_id: 1
}
stop_time_update {
stop_sequence: 11
stop_id: "South Station"
}
}
}
```
That StopTimeUpdate does not have any useful information, so instead we drop
it from the rendered version. This had some knock-on effects on test cases,
where we weren't providing any data for StopTimeUpdates we expected to be in
the output.

fix: filter out empty StopTimeUpdate records

---

lib/concentrate/encoder/gtfs_realtime_helpers.ex
test/concentrate/encoder/producer_consumer_test.exs
test/concentrate/encoder/trip_updates_test.exs

Once we started filtering out some StopTimeUpdate values, it became possible
to end up with an empty list of StopTimeUpdates. Since we don't have any
updates, there's nothing to do with that TripUpdate and we drop it entirely.
This results in failures for some other tests, where there wasn't enough
information in the StopTimeUpdate to render.

fix: don't render empty TripUpdates

---

lib/concentrate/parser/gtfs_realtime.ex
test/concentrate/parser/gtfs_realtime_test.exs

One of our sources is returning invalid data in this field: validate that
it's correct and drop it if not.

fix: handle invalid `start_time`

---

lib/concentrate/group_filter/time_out_of_range.ex
test/concentrate/group_filter/time_out_of_range_test.exs

Asana ticket: [increase allowed past time in TimeOutOfRange  GroupFilter](https://app.asana.com/0/584764604969369/1155876947667457/f)
Bumped up `@min_time_in_past` in `Concentrate.GroupFilter.TimeOutOfRange` from one minute to 10 minutes. Slightly modified assertions in `"removes StopTimeUpdates if they're in the past or future"` block to ensure we still cover all cases. Also changed  assertion in `"keeps stop time update if a previous update was in the range"` to more accurately match description.

refactor: increase the lookback time in TimeOutOfRange from one minute to 10 minutes

---

config/config.exs
lib/concentrate/encoder/gtfs_realtime_helpers.ex
lib/concentrate/group_filter/trip_update_timestamp.ex
lib/concentrate/parser/gtfs_realtime.ex
lib/concentrate/parser/gtfs_realtime_enhanced.ex
lib/concentrate/trip_update.ex
test/concentrate/encoder/trip_updates/json_test.exs
test/concentrate/encoder/trip_updates_enhanced_test.exs
test/concentrate/encoder/trip_updates_test.exs
test/concentrate/group_filter/trip_update_timestamp_test.exs
test/concentrate/parser/gtfs_realtime_enhanced_test.exs
test/concentrate/parser/gtfs_realtime_test.exs

Asana ticket: [populate timestamp in TripUpdates.pb if there's a corresponding timestamp for the Vehicle](https://app.asana.com/0/584764604969369/1150546384019615)
Changes:
* Updated relevant `parsers` to use `timestamp` on `TripUpdate` if it exists
* Added `Concentrate.GroupFilter.TripUpdateTimestamp` to use the timestamp from corresponding `VehiclePosition`
* Updated `encoders` to use the `timestamp` value on a `TripUpdate`

refactor: populate timestamp on TripUpdate using corresponding value in VehiclePosition

---

Dockerfile
rel/config.exs

- name of the Mix task is `distillery.release`
- name of the config provider is `Distillery.Releases.Config`

fix: update build steps for Distillery 2.1

---

Dockerfile

It looks like CI is also re-copying the mix.exs and mix.lock files, which is
confusing the build step.

fix: explicitly specify which directories to copy

---

config/config.exs
guides/architecture.md
lib/concentrate/filter/alert/supervisor.ex
lib/concentrate/filter/gtfs/supervisor.ex
lib/concentrate/producer/httpoison.ex
lib/concentrate/producer/httpoison/state_machine.ex
lib/concentrate/supervisor/pipeline.ex
test/concentrate/producer/httpoison/property_test.exs
test/concentrate/producer/httpoison/state_machine_test.exs
test/concentrate/producer/httpoison_test.exs

It's better base to build #82 on top of.

refactor: make the HTTP producer configurable

---

lib/concentrate/parser/gtfs_realtime_enhanced.ex
test/concentrate/encoder/vehicle_positions_enhanced_test.exs
test/concentrate/parser/gtfs_realtime_enhanced_test.exs

We parsed this out of Protobuf TripUpdates, but not for the enhanced
feeds. This means we were dropping that information for our subway feeds,
which are now enhanced.

fix(GTFSRealtimeEnhanced): parse the `vehicle_id` for TripUpdate

---

config/config.exs
lib/concentrate/trip_update.ex
test/concentrate/trip_update_test.exs

- disable the VehiclePastStop filter so we don't drop StopTimeUpdates earlier than the schedule
- sort TripUpdates by start_date/time to (hopefull) work around a vendor issue

two patches: disable vehiclepaststop and sort trip updates

---

lib/concentrate/parser/gtfs_realtime.ex
lib/concentrate/parser/gtfs_realtime_enhanced.ex
lib/concentrate/parser/helpers.ex
lib/concentrate/producer/httpoison.ex
test/concentrate/parser/gtfs_realtime_enhanced_test.exs
test/concentrate/parser/gtfs_realtime_test.exs
test/concentrate/parser/helpers_test.exs
test/concentrate/producer/httpoison_test.exs

Asana ticket: [🚝 log vehicle timestamps which are greater than the reported feed timestamp](https://app.asana.com/0/584764604969369/1168026177896885/f)

Log vehicle timestamp mismatch

---

lib/concentrate/parser/gtfs_realtime.ex
lib/concentrate/parser/gtfs_realtime_enhanced.ex
lib/concentrate/parser/helpers.ex
test/concentrate/parser/gtfs_realtime_enhanced_test.exs

The normal VehiclePositions already supported this, but not the enhanced parser.

support routes/excluded_routes when parsing enhanced VehiclePositions

---

.github/workflows/elixir.yml
.github/workflows/report_coverage.yml

Since this doesn't run any untrusted code, it has a GITHUB_TOKEN with permission to post to the repository. You can see the example working in my fork with this PR: https://github.com/paulswartz/concentrate/pull/4
The `pull_request_target` failure is known, and also happening on the `master` branch. The `pull_request` GitHub Action is the correct once.

ci: report code coverage as a `workflow_run` step

---

.github/workflows/elixir.yml
.github/workflows/report_coverage.yml

This lets us use the single `.tool-versions` configuration for installation, rather than needing to maintain the current version in multiple places. Caching the builds is slow the first time, but quick in future runs.

ci: use ASDF to install Elixir/Erlang

---

config/config.exs
lib/concentrate/filter/gtfs/helpers.ex
lib/concentrate/filter/gtfs/pickup_drop_off.ex
lib/concentrate/filter/gtfs/stop_ids.ex
lib/concentrate/filter/gtfs/supervisor.ex
lib/concentrate/filter/include_stop_id.ex
lib/concentrate/filter/null_stop_sequence.ex
lib/concentrate/stop_time_update.ex
test/concentrate/filter/gtfs/helpers_test.exs
test/concentrate/filter/gtfs/stop_ids_test.exs
test/concentrate/filter/include_stop_id_test.exs
test/concentrate/filter/null_stop_sequence_test.exs
test/concentrate/stop_time_update_test.exs
test/support/filter/fakes.ex

Previously we merged StopTimeUpdates using a "key" of trip ID + stop ID + stop sequence. Since stop ID and sequence are both optional (only one needs to be present), this created the potential for duplicates: two updates that referred to the same stop would not be merged if one of them used a sequence and the other used a stop ID.
Given:
1. it's not universally possible to merge StopTimeUpdates without a stop sequence (it's required if a trip contains a loop)
2. merging updates correctly using "maybe stop ID or sequence or both" would require significant changes to the merging system
3. grouping and the `RemoveUnneededTimes` filter assume the presence of stop sequences
4. all our current input feeds either include stop sequences already or are planned to
...we can simplify things by …

fix: require `stop_sequence` for StopTimeUpdates

---

.github/workflows/dev-green.yml

When https://github.com/mbta/devops/pull/381 is applied, the dev green service will be renamed to concentrate-dev-green. This PR aligns the deployment workflow with that change.

fix: align ECS service name with Terraform

---

.tool-versions
Dockerfile

The project's previous version of Erlang no longer builds on current versions of macOS, which is a blocker for continued work on it.

deps: update to latest release of Erlang 23

---

.github/workflows/dev.yml
.github/workflows/elixir.yml
.tool-versions
Dockerfile
lib/concentrate/producer/httpoison/state_machine.ex
test/concentrate/encoder/trip_updates_enhanced_test.exs

Upgrades project to Erlang 24 and Elixir 1.11, so that it can be built on Ubuntu 22.04. This is an alternative approach to [using Docker to run the tests](https://github.com/mbta/concentrate/pull/262). 
Main concern is [this fix](https://github.com/mbta/concentrate/pull/263/files#diff-2c04e9646ab4e9b75b4af509112dcca2509622bbaaeaf5be645d03b583edcb97R16) - is it a problem that encoding and decoding the list results in a slight reordering? I would guess not, but it's a guess 😄 
**Asana Ticket:** [Concentrate CI runs on Ubuntu 22.04](https://app.asana.com/0/584764604969369/1203566390446235/f)

Erlang 24 upgrade

---

config/config.exs
lib/concentrate/group_filter/remove_uncertain_stop_time_updates.ex
test/concentrate/group_filter/remove_uncertain_stop_time_updates_test.exs

**Asana Ticket:** [[extra] 🧠 Temporarily suppress terminal/reverse trip predictions for Red Line and Blue Line in Concentrate](https://app.asana.com/0/584764604969369/1204348457726555/f)
Adds a new GroupFilter that removes uncertain StopTimeUpdates from a group that match a route_id and uncertainty value specified as a map in `config.exs`. Also updates `config.exs` to suppress Red and Blue line terminal and reverse predictions while we wait for schedules to recover.

Temporarily suppress terminal/reverse trip predictions for Red Line and Blue Line in Concentrate

---

.tool-versions
config/config.exs
config/dev.exs
config/prod.exs
config/test.exs
lib/concentrate/parser/helpers.ex
lib/concentrate/producer/httpoison/state_machine.ex
mix.exs

No Ticket
Updates to Elixir 1.14 and Erlang 25. Erlang 26 was not used due to critical bugs in OTP-26:
https://github.com/erlang/otp/issues/7132
https://github.com/erlang/otp/issues/7230

chore: Elixir 1.14 and Erlang 25

---

config/config.exs
lib/concentrate/group_filter/time_travel.ex
lib/concentrate/stop_time_update.ex
test/concentrate/group_filter/time_travel_test.exs
test/concentrate/stop_time_update_test.exs

**Asana Ticket:** 
[🧠 🐛 Don't mix predictions: Multiple sources to Swiftly, same trip](https://app.asana.com/0/584764604969369/1204277338626227/f)
[🧠 🐛 Don't mix predictions: Multiple buses, same trip](https://app.asana.com/0/584764604969369/1204277338626221/f)
This ensures that we are always using times from the same prediction when merging StopTimeUpdates and filters trips that suggest we'll arrive at a later stop before departing a previous one.

Don't mix predictions

---

config/config.exs

**Asana Ticket:** [[extra] 🧠 Re-enable terminal/reverse trip predictions for Blue Line](https://app.asana.com/0/584764604969369/1204944794413796/f)
Removes the Blue Line filter that was added previously here - https://github.com/mbta/concentrate/pull/277

chore: remove the removal of blue line predictions

---

lib/concentrate/group_filter/cancelled_trip.ex
lib/concentrate/stop_time_update.ex
test/concentrate/group_filter/cancelled_trip_test.exs
test/concentrate/stop_time_update_test.exs

Cancelled trip group filter now filters out trips where all stop updates have SKIPPED status
**Asana Ticket:** [Add trip-level schedule_relationship for canceled bus trips](https://app.asana.com/0/505721188639414/1204778267687026/f)
This change surfaces a trip-level schedule relationship of CANCELED for bus trips where all of the associated stop time updates have been given the SKIPPED status.

Update to cancelled_trip group filter 

---

config/config.exs
lib/concentrate/group_filter/scheduled_stop_times.ex
lib/concentrate/parser/gtfs_realtime_enhanced.ex
test/concentrate/group_filter/scheduled_stop_times_test.exs
test/concentrate/parser/gtfs_realtime_enhanced_test.exs

**Asana Ticket:** [🚆Keolis Feed Transition](https://app.asana.com/0/584764604969369/1204680576534832/f)
Does 3 main things:
1) Adds the Keolis GTFS enhanced feeds to the local configuration
2) Makes the handling of on time statuses no longer case sensitive
3) Overrides the boarding statuses provided by Keolis to match those in Commuter Rail Boarding

feat: Keolis realtime gtfs

---

config/config.exs

**Asana Ticket:** [[extra] 🧠 Temporarily suppress terminal/reverse trip predictions for Red Line in Concentrate](https://app.asana.com/0/505721188639414/1205390570992202/f)
Re-instates the red line config originally added in this PR: https://github.com/mbta/concentrate/pull/277

fix: turn off terminal predictions for RL for now

---

config/config.exs

Revert "fix: turn off terminal predictions for RL for now"

---

config/config.exs
lib/concentrate.ex
lib/concentrate/encoder/producer_consumer.ex
lib/concentrate/feed_update.ex
lib/concentrate/merge/table.ex
lib/concentrate/merge_filter.ex
lib/concentrate/mergeable.ex
lib/concentrate/sink/filesystem.ex
lib/concentrate/sink/mqtt.ex
lib/concentrate/sink/s3.ex
lib/concentrate/stop_time_update.ex
lib/concentrate/supervisor/pipeline.ex
lib/concentrate/trip_descriptor.ex
lib/concentrate/vehicle_position.ex
test/concentrate/merge/table_test.exs
test/concentrate/merge_filter_test.exs
test/concentrate/sink/mqtt_test.exs
test/concentrate_test.exs
test/support/test_mergeable.ex

Sends DIFFERENTIAL updates via MQTT, to reduce latency on processing Vehicle Positions.
**Asana Ticket:** [Concentrate: avoid batching updates in the MQTT -> MergeTable -> MQTT pipeline](https://app.asana.com/0/1205365039348894/1205365039348911/f)

feat: send partial updates via MQTT sink

---

lib/concentrate/producer/mqtt.ex
lib/concentrate/sink/mqtt.ex

**Asana Ticket:** [test handling of failures/restarts with a multi-AZ broker](https://app.asana.com/0/584764604969369/1205632203703839/f)
The default is to reconnect starting at 5 seconds, expontentially going up to 5 minutes. This starts at 1 second and goes up to 1 minute.

fix(mqtt): reconnect more quickly

---

lib/concentrate/encoder/vehicle_positions.ex
lib/concentrate/encoder/vehicle_positions_enhanced.ex
lib/concentrate/vehicle_position.ex
test/concentrate/encoder/vehicle_positions_enhanced_test.exs
test/concentrate/encoder/vehicle_positions_test.exs
test/concentrate/vehicle_position_test.exs

Previously, we'd always take the status from the second VehiclePosition. For higher-frequency feeds, this would likely always mean `IN_TRANSIT_TO`. Now, we don't set a default except when encoding. This allows us to take a value from a earlier update.
**Asana Ticket:** [do we keep STOPPED_AT when merging?](https://app.asana.com/0/1205365039348894/1205645288310907/f)

feat: improve merging of VehiclePosition.status()

---

.github/workflows/dev-green.yml
.github/workflows/dev.yml
.github/workflows/prod.yml

**Asana Ticket:** [Update application repos to use the new version of the GitHub action(s) (v2 tag)](https://app.asana.com/0/1113179098808463/1205367032564122/f)
This PR updates the deploy workflow to use v2 of the shared `build-push-ecr` and `deploy-ecs` actions. These updated actions assume an IAM role instead of relying on long-lasting AWS keys for an IAM user

Chore: Update GitHub actions to use assumed role

---

guides/configuration.md
lib/concentrate.ex
lib/concentrate/supervisor/pipeline.ex
test/concentrate/supervisor/pipeline_test.exs
test/concentrate_test.exs

FileTap is responsible for logging the files which went into Concentrate. When we only had a single S3 sink, it was easy to send all the FileTap files to the same sink. With the introduction of MQTT, we don't want to send the FileTap files to the MQTT broker, so we need to add a bit of optional configuration about which sinks accept the FileTap files.
See also mbta/devops#1289
**Asana Ticket:** [Concentrate: don't send FileTap files to the MQTT sink](https://app.asana.com/0/1205365039348894/1205748776837980/f)

feat: allow configuring which Sinks accept FileTap files

---

.github/workflows/elixir.yml
config/config.exs
lib/concentrate/reporter/vehicle_time_travel.ex
lib/concentrate/source_reporter/basic.ex
test/concentrate/reporter/vehicle_time_travel_test.exs
test/concentrate/source_reporter/basic_test.exs

**Asana Ticket:** [Green Line trains going backwards in time](https://app.asana.com/0/1204137169527258/1205763132199440/f)
Logs when vehicles have a timestamp earlier than the current timestamp.

feat: log when VehiclePositions move backwards in time

---

.github/workflows/prod.yml

**Asana Ticket:** No ticket
This looks like it only affects naming within github actions. The elixir config is already `config/prod.exs`
Update deploy name and environment from "production" to "prod" to match other repos (rtr etc)

ci: update deploy name and environment from "production" to "prod"

---

Dockerfile

Quick fix to https://github.com/mbta/concentrate/pull/354 since I forgot to update the Dockerfile.

fix: bump versions in Dockerfile

---

.github/workflows/elixir.yml

**Asana Ticket:** NO TICKET
[Please include a brief description of what was changed]

fix: use upload-artifact v4 to fix workflow failures

---

lib/concentrate/gtfs/supervisor.ex

**Asana Ticket:** [Bus trips with block waivers not marked as cancelled](https://app.asana.com/0/1204137169527258/1208580923116010)
Ensure the routes table is populated with route records so that bus trips with block waivers are cancelled.
Debugging bus trips that had skipped stops but weren't marked as cancelled, @boringcactus observed that it is expected for them to be marked as cancelled [here](https://github.com/mbta/concentrate/blob/981d82250adff8080091d3afc743df6e9b62576d/lib/concentrate/group_filter/cancelled_trip.ex#L52). It seemed the `bus_block_waiver?` check might be failing. I observed no logs in Splunk from `Concentrate.GTFS.Routes` as expected [here](https://github.com/mbta/concentrate/blob/981d82250adff8080091d3afc743df6e9b62576d/lib/concentrate/gtfs/routes.ex#L42), and …

GTFS.Routes subscribed to :gtfs_producer

---

lib/concentrate/filter/alert/closed_stops.ex
lib/concentrate/group_filter/closed_stop.ex
test/concentrate/filter/alert/closed_stops_test.exs
test/support/filter/fakes.ex

Two updates for how we treat closed stops:
- take the route into account when checking for closed stops
- only treat a NO_SERVICE stop as closed if it's affecting both BOARD and EXIT activities
Seems to be working better on dev-green: 
- https://api-dev-green.mbtace.com/predictions?filter[stop]=70196&filter[route]=Green-B (not skipped)
- https://api-dev-green.mbtace.com/predictions?filter[stop]=70196&filter[route]=Green-D (still skipped)

Closed stop on route

---

.github/workflows/elixir.yml
README.md
docker-compose.yml
mosquitto/mosquitto.conf
mosquitto/passwd
test/concentrate/producer/mqtt_test.exs
test/concentrate/sink/mqtt_test.exs

**Asana Ticket:** [[extra] Make Concentrate tests work locally](https://app.asana.com/0/584764604969369/1209056551063150/f)
This is largely based off of mbta/api#766.

Local test MQTT broker

---

.envrc.example
.gitignore
README.md
lib/concentrate/group_filter/cancelled_trip.ex
lib/concentrate/gtfs/stop_times.ex
test/concentrate/group_filter/cancelled_trip_test.exs
test/concentrate/gtfs/stop_times_test.exs
test/support/filter/fakes.ex

**Asana Ticket:** [🧠 Re-implement SKIPPED StopTimeUpdates for CANCELLED trips](https://app.asana.com/1/15492006741476/project/584764604969369/task/1210575419129897?focus=true)
Problem:
The PR that we previously deployed to add SKIPPED StopTimeUpdates for CANCELLED trips resulted in stop information "flickering" for the buses such that the stop to which a bus was headed would appear and disappear intermittently.
Solution:
This was happening because the `bus_block_waiver?/2` function returned `true` for trips with no `StopTimeUpdates`, and RTR intermittently gets bus trips with no `StopTimeUpdates` (likely from Busloc?). Previously, these trips were most likely ignored, but now they cause us to cancel bus trips unnecessarily, which causes us to …

fix(cancelled-trips): re-implement making skipped stop time updates for cancelled trips

---

lib/concentrate/encoder/trip_updates_enhanced.ex
test/concentrate/encoder/trip_updates_enhanced_test.exs

**Asana Ticket:** [[extra] 🧠 Publish arrival and departure times within non-revenue StopTimeUpdates through Concentrate](https://app.asana.com/1/15492006741476/project/584764604969369/task/1210880282700169?focus=true)
Currently running on dev-blue. I've confirmed that STUs with `passthrough_time` are no longer having their arrival / departure times filtered out in the enhanced feed.

Include arrival and departure with passthrough
